"""
Script for running simulation of 2011 Tohoku tsunami

Source data such as elevation and boundary data is assumed to be available in
directories specified by project.py
The output sww file is stored in directory named after the scenario, i.e
slide or fixed_wave.

The scenario is defined by a triangular mesh created from project.polygon,
the elevation data and a tsunami wave generated by a submarine mass failure.

Stephen Roberts  2012-present
"""

#------------------------------------------------------------------------------
# Import necessary modules
#------------------------------------------------------------------------------
# Standard modules

from __future__ import print_function

import os
from numpy import allclose
import time
import sys
import numpy as np
# Related major packages
import anuga


from anuga import distribute, myid, numprocs, finalize, barrier

import project


tide = -0.45

# Change this to run alternative versions of the slip field. 
# The slip field will be saved to the output directory
iseed = 2


#===============================================================================
# Sequential Section
# Only create sequential domain on processor 0
#===============================================================================
if myid == 0:
    #------------------------------------------------------------------------------
    # Create the triangular mesh and domain based on
    # overall clipping polygon with a tagged
    # boundary and interior regions as defined in project.py
    #------------------------------------------------------------------------------
    print ('project name: ', project.name_stem)
    domain = anuga.create_domain_from_regions(project.bounding_polygon,
                                        boundary_tags={'bottom': [0],
                                                       'ocean_east': [1],
                                                       'top': [2],
                                                       'onshore': [3]},
                                        maximum_triangle_area=project.res_whole,
                                        mesh_filename=project.meshname,
                                        interior_regions=project.interior_regions,
                                        use_cache=True,
                                        verbose=True)

    # Print some stats about mesh and domain
    print ('Number of triangles = ', len(domain))
    print ('The extent is ', domain.get_extent())
    print (domain.statistics())


    #------------------------------------------------------------------------------
    # Setup parameters of computational domain
    #------------------------------------------------------------------------------
    Name = 'Okada_%g'% iseed
    domain.set_name('Tohoku_' + Name) # Name of sww file
    domain.set_datadir('_output_' + Name)        # Store sww output here
    domain.set_minimum_storable_height(0.01)      # Store only depth > 1cm
    #domain.set_flow_algorithm('DE0')

    #------------------------------------------------------------------------------
    # Setup initial conditions
    #------------------------------------------------------------------------------
    domain.set_quantity('elevation',
                        filename=project.name_stem + '.pts',
                        use_cache=True,
                        verbose=project.verbose,
                        alpha=0.1)

    domain.set_quantity('stage', tide)


    # Run one instance of the okada KL field
    import okada_kl_subfaults as okl

    x = domain.centroid_coordinates[:,0]
    y = domain.centroid_coordinates[:,1]

    uE,uN,uZ,slips = okl.deformation(x, y, xoff=300000.0, yoff=250000.0, E_subfault=5, N_subfault=10, iseed=1001)
    
    

    Stage = domain.quantities['stage'].centroid_values
    Stage[:] = Stage + uZ

    #domain.add_quantity('stage',
    #                   function=okada_deformation,
    #                   verbose=project.verbose,
    #                   location='centroids')

    domain.set_quantity('friction', 0.0)
else:
    domain = None

#-------------------------------------------------------------------------------
# Distribute domain
#-------------------------------------------------------------------------------
domain = distribute(domain,verbose=project.verbose)


#===============================================================================
# Parallel Section
#===============================================================================

domain.set_quantities_to_be_stored({'stage' : 2,
                                    'xmomentum' : 2,
                                    'ymomentum' : 2,
                                    'elevation' : 2})
domain.set_quantities_to_be_monitored(['stage', 'xmomentum', 'ymomentum'])



if myid ==0: print ('running project:', project.scenario)
#------------------------------------------------------------------------------
# Setup boundary conditions
#------------------------------------------------------------------------------
#print 'Available boundary tags', domain.get_boundary_tags()

def tide_fun(t):
    return tide

Bd = anuga.Dirichlet_boundary([tide, 0, 0]) # Mean water level
#Bs = anuga.Transmissive_stage_zero_momentum_boundary(domain) # Neutral boundary
Bs = anuga.Transmissive_n_momentum_zero_t_momentum_set_stage_boundary(domain,tide_fun)
Bf = anuga.Flather_external_stage_zero_velocity_boundary(domain,tide_fun)
Bt = anuga.Transmissive_boundary(domain) # Neutral boundary
Br = anuga.Reflective_boundary(domain)
# Boundary conditions for slide scenario
domain.set_boundary({'ocean_east': Bf,
                         'bottom': Bf,
                         'onshore': Br,
                         'top': Bf})
if myid==0 : print (domain.boundary_statistics(tags=['ocean_east','onshore']))
#------------------------------------------------------------------------------
# Evolve system through time
#------------------------------------------------------------------------------
# initial time

t0 = time.time()
min = 60
hour = 3600

# source file

# Initial run without any event
for t in domain.evolve(yieldstep=5*min, finaltime=4*hour):

    domain.write_time()


domain.sww_merge(delete_old=True)

if anuga.myid == 0:
    np.savetxt('_output_' + Name + '/slips.txt', slips)

print ('That took %.2f seconds' %(time.time()-t0))


anuga.finalize()
